### ISSUE TITLE
Support pageSize in z system 

### ISSUE THREAD

**Issue by jannyhou2022** [knqyf263/go-rpmdb#22]
Hey @knqyf263 thank you for creating this project 👏  

Scan tool anchore is using this module as a dependency in [syft](https://github.com/anchore/syft). When our team scans z system images, it failed with invalid page size error:

> unable to catalog rpmdb package=/var/lib/rpm/Packages: unexpected page size: 1048576

My colleague finds the code here:

https://github.com/knqyf263/go-rpmdb/blob/5101b033fa0d5d4724a81602fd24bc0a27578c43/pkg/bdb/hash_metadata_page.go#L24

it should have use BigEndian for reading the Packages file on s390x(z system), then it will get a normal pagesize 4096 just as x86.

It would be good if `go-rpmdb` can support z systems too.

**Comment by bcrochet** [comment]
This should actually be fixed by #25. Can you test that it does?

**Comment by bcrochet** [comment]
@knqyf263 I would consider this fixed by #25 and close. If the reporter needs to re-open, they can.

**Comment by knqyf263** [comment]
Got it. Thanks!
