### ISSUE TITLE
SigMD5 ending in zeroes are truncated

### ISSUE THREAD

**Issue by eredwine** [knqyf263/go-rpmdb#44]
Currently the UBI8 `libuuid` rpm has an SIGMD5 value of `c1e561f13d39aee443a1f00258fba000`.

```
rpm -qa --queryformat "\{Name: \"%{NAME}\", Digest: \"md5:%{SIGMD5}\"\}\n"
{Name: "libuuid", Digest: "md5:c1e561f13d39aee443a1f00258fba000"}
```

 but the SIGMD5 value is loaded as `c1e561f13d39aee443a1f00258fba0`. 
```
package main

import (
	"fmt"
	"log"

	rpmdb "github.com/knqyf263/go-rpmdb/pkg"
)

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	db, err := rpmdb.Open("./Packages")
	if err != nil {
		return err
	}
	pkgList, err := db.ListPackages()
	if err != nil {
		return err
	}

	fmt.Println("Packages:")
	for _, pkg := range pkgList {
		fmt.Printf("\t%+s %+s\n", *&pkg.Name, *&pkg.SigMD5)
	}

	fmt.Printf("[Total Packages: %d]\n", len(pkgList))
	return nil
}
```

```
./package-checker 
Packages:
        libuuid c1e561f13d39aee443a1f00258fba0
[Total Packages: 1]
```

The attached [Packages.zip](https://github.com/knqyf263/go-rpmdb/files/12807084/Packages.zip) file contains the `libuuid` rpm that is experiencing the error.

**Comment by knqyf263** [comment]
I think `bytes.TrimRight` should be replaced with `bytes.TrimSuffi`. I welcome contributions 👍 
https://github.com/DmitriyLewen/go-rpmdb/blob/801cdbd76e632491a3be72951364749fffce5ca5/pkg/package.go#L237

**Comment by eredwine** [comment]
> I think `bytes.TrimRight` should be replaced with `bytes.TrimSuffi`. I welcome contributions 👍 https://github.com/DmitriyLewen/go-rpmdb/blob/801cdbd76e632491a3be72951364749fffce5ca5/pkg/package.go#L237

I don't think `bytes.TrimSuffix` would work either. MD5 checksums are always 16 bytes in size so any trimming would result in incomplete data.

**Comment by knqyf263** [comment]
It terminates with null

**Comment by eredwine** [comment]
Yea, I don't think there is a null since it is not a string. I checked the length of the byte slice and it is 16 bytes. So, that doesn't leave room for a null terminator since an MD5 checksum needs 16 bytes. 

But, I could see doing something like `ie.Data[0:16]` in case there was one in some future version of the RPM spec.

**Comment by knqyf263** [comment]
OK

**Comment by knqyf263** [comment]
https://github.com/knqyf263/go-rpmdb/pull/45
