### ISSUE TITLE
Request for Version Tagging in go-rpmdb

### ISSUE THREAD

**Issue by ryancurrah** [knqyf263/go-rpmdb#50]
Hi @knqyf263,

I’ve been using your Go module, go-rpmdb, and I’ve found it really useful. I wanted to suggest adding version tags. This would help with being able to reference stable versions, make it easier to manage dependencies, and signal ongoing maintenance. 

It’s a small change that could really enhance your module’s usability.

Thanks for considering this!

Best,
Ryan Currah

**Comment by rjammala** [comment]
@knqyf263 : is it possible to add version tags?

**Comment by knqyf263** [comment]
This repository is already stable and hasn't changed much, so I think it's enough to refer to the main branch, what do you think?

**Comment by rjammala** [comment]
If possible please add a version tag otherwise we can use it from main. Thanks.

**Comment by knqyf263** [comment]
Done
https://github.com/knqyf263/go-rpmdb/releases/tag/v0.1.0
